In [1]:
import pandas as pd
df = pd.read_csv('adult.csv')
df

,age,workclass,education,marital-status,occupation,race,gender,hours-per-week,income
0,20-30,Private,11th,Never-married,Machine-op-inspct,Black,0,20-40,<=50K
1,30-40,Private,HS-grad,Married-civ-spouse,Farming-fishing,White,0,40-60,<=50K
2,20-30,Local-gov,Assoc-acdm,Married-civ-spouse,Protective-serv,White,0,20-40,>50K
3,40-50,Private,Some-college,Married-civ-spouse,Machine-op-inspct,Black,0,20-40,>50K
4,30-40,Private,10th,Never-married,Other-service,White,0,20-40,<=50K
5,60-70,Self-emp-not-inc,Prof-school,Married-civ-spouse,Prof-specialty,White,0,20-40,>50K
6,20-30,Private,Some-college,Never-married,Other-service,White,1,20-40,<=50K
7,50-60,Private,7th-8th,Married-civ-spouse,Craft-repair,White,0,0-20,<=50K
8,60-70,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,White,0,20-40,>50K
9,30-40,Federal-gov,Bachelors,Married-civ-spouse,Adm-clerical,White,0,20-40,<=50K
10,20-30,Private,HS-grad,Never-married,Adm-clerical,White,1,20-40,<=50K
11,40-50,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,White,0,40-60,>50K
12,40-50,Private,Masters,Married-civ-spouse,Exec-managerial,White,0,40-60,>50K
13,0-20,State-gov,Some-college,Never-married,Other-service,White,0,20-40,<=50K
14,40-50,Private,HS-grad,Married-civ-spouse,Adm-clerical,White,1,20-40,<=50K
15,30-40,Private,HS-grad,Widowed,Machine-op-inspct,White,1,0-20,<=50K
16,30-40,Private,Doctorate,Married-civ-spouse,Prof-specialty,Asian-Pac-Islander,0,40-60,>50K
17,30-40,Private,Bachelors,Married-civ-spouse,Tech-support,White,0,40-60,>50K
18,30-40,Private,Some-college,Never-married,Other-service,Black,1,20-40,<=50K
19,20-30,Private,Bachelors,Never-married,Prof-specialty,White,0,40-60,<=50K
20,20-30,Private,Bachelors,Married-civ-spouse,Prof-specialty,White,0,20-40,<=50K
21,40-50,Self-emp-not-inc,HS-grad,Married-civ-spouse,Craft-repair,White,0,80-100,>50K
22,20-30,Private,HS-grad,Never-married,Adm-clerical,White,0,0-20,<=50K
23,20-30,Private,HS-grad,Separated,Machine-op-inspct,Black,0,40-60,<=50K
24,50-60,Private,HS-grad,Married-civ-spouse,Craft-repair,White,0,20-40,<=50K
25,30-40,Self-emp-not-inc,Some-college,Never-married,Prof-specialty,White,0,40-60,<=50K
26,40-50,State-gov,Some-college,Married-civ-spouse,Exec-managerial,Black,0,20-40,>50K
27,50-60,Self-emp-not-inc,11th,Widowed,Other-service,White,1,40-60,<=50K
28,20-30,Self-emp-not-inc,Bachelors,Never-married,Sales,White,0,40-60,<=50K
29,20-30,Local-gov,Some-college,Married-civ-spouse,Protective-serv,White,0,20-40,<=50K
...,...,...,...,...,...,...,...,...,...
46003,30-40,Private,10th,Married-civ-spouse,Transport-moving,White,0,20-40,<=50K
46004,20-30,Private,Some-college,Never-married,Adm-clerical,White,0,20-40,<=50K
46005,30-40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,White,1,20-40,<=50K
46006,20-30,Private,HS-grad,Separated,Sales,White,1,20-40,<=50K
46007,30-40,Private,Doctorate,Married-civ-spouse,Prof-specialty,White,0,40-60,>50K
46008,50-60,Private,Bachelors,Married-civ-spouse,Exec-managerial,Asian-Pac-Islander,0,40-60,>50K
46009,30-40,Private,Some-college,Divorced,Adm-clerical,White,1,20-40,<=50K
46010,20-30,Private,12th,Never-married,Protective-serv,Black,0,20-40,<=50K
46011,30-40,Private,Bachelors,Never-married,Exec-managerial,White,1,40-60,>50K
46012,20-30,Private,HS-grad,Never-married,Craft-repair,Black,0,40-60,<=50K
46013,30-40,Private,Bachelors,Divorced,Prof-specialty,Black,1,40-60,>50K
46014,40-50,State-gov,HS-grad,Separated,Adm-clerical,White,1,20-40,<=50K
46015,40-50,Local-gov,Assoc-acdm,Divorced,Prof-specialty,White,1,40-60,<=50K
46016,30-40,Private,Masters,Divorced,Other-service,Other,1,20-40,<=50K
46017,30-40,Local-gov,Assoc-acdm,Married-civ-spouse,Adm-clerical,White,1,0-20,>50K
46018,30-40,Private,Assoc-acdm,Divorced,Tech-support,White,1,20-40,<=50K
46019,40-50,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,White,0,20-40,<=50K
46020,60-70,Self-emp-not-inc,Prof-school,Never-married,Prof-specialty,White,0,40-60,<=50K
46021,40-50,State-gov,Some-college,Divorced,Adm-clerical,White,1,20-40,<=50K
46022,40-50,Self-emp-not-inc,Some-college,Married-civ-spouse,Craft-repair,White,0,40-60,<=50K
46023,30-40,Private,10th,Married-civ-spouse,Handlers-cleaners,Amer-Indian-Eskimo,0,20-40,<=50K
46024,40-50,Private,Assoc-voc,Married-civ-spouse,Sales,White,0,40-60,<=50K
46025,30-40,Private,Masters,Never-married,Tech-support,Asian-Pac-Islander,0,0-20,<=50K
46026,50-60,Private,Masters,Married-civ-spouse,Exec-managerial,White,0,20-40,>50K
46027,20-30,Private,Some-college,Never-married,Protective-serv,White,0,20-40,<=50K
46028,20-30,Private,Assoc-acdm,Married-civ-spouse,Tech-support,White,1,20-40,<=50K
46029,30-40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,White,0,20-40,>50K
46030,50-60,Private,HS-grad,Widowed,Adm-clerical,White,1,20-40,<=50K
46031,20-30,Private,HS-grad,Never-married,Adm-clerical,White,0,0-20,<=50K
46032,50-60,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,White,1,20-40,>50K

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46033 entries, 0 to 46032
Data columns (total 9 columns):
age               46033 non-null object
workclass         46033 non-null object
education         46033 non-null object
marital-status    46033 non-null object
occupation        46033 non-null object
race              46033 non-null object
gender            46033 non-null int64
hours-per-week    46033 non-null object
income            46033 non-null object
dtypes: int64(1), object(8)
memory usage: 3.2+ MB

In [3]:
df = df.astype(str)
data = df.values.tolist()

In [4]:
from apyori import apriori

#建立rule, 設定參數
#變成list
rules = list(apriori(data, min_support= 0.2, min_confidence= 0.9))
rules

ModuleNotFoundError: No module named 'apyori'

In [ ]:
result = pd.DataFrame()
for item in rules:
    series = pd.Series({"Rule":item[0],"Support":item[1],"Confidence":item[2][0][2]})
    result = result.append(series, ignore_index=True)

In [ ]:
result.sort_values(by= ['Confidence'], ascending=False)